### ISSUE TITLE
Password copied to a clipboard has multiple space characters at the end of the password that are not part of the password

### ISSUE THREAD

**Issue by kaspar-naaber** [sadovnychyi/alfred-chrome-passwords#1]
Currently it seems like something is a bit broken with this workflow. For example when my password should be
```
"12345"
```
 it will return
```
"12345        "
```

**Comment by sadovnychyi** [comment]
It has been resolved in another similar tool, somewhere [here](https://github.com/sadovnychyi/chrome-passwords-cli/blob/master/pass#L42-L48).

**Comment by kaspar-naaber** [comment]
I tried to apply it, but I'm not that familiar with the Python language and I failed. :P It would be nice if you could fix this in this project also. Thanks!

**Comment by sadovnychyi** [comment]
Should be fixed now.
